#
# Secrets Manager.
#
# Every value here is generated by Terraform. None is ever supplied by hand,
# printed to a terminal, or committed. The Secrets Store CSI driver mounts them
# into pods as files at runtime.
#
# recovery_window_in_days = 0 is essential for an environment that is rebuilt
# daily. The default is a 7-30 day recovery window during which the name stays
# reserved, so tomorrow's apply would fail with "a secret with this name is
# scheduled for deletion". Zero means the delete is immediate and the name is
# free again straight away.
#

locals {
  secret_prefix = "${var.project}/${var.environment}"
}

# ----------------------------------------------------------------- database

# Deliberately shaped like the JSON an RDS-managed rotation would produce, so
# the SecretProviderClass jmesPath in the Helm chart works unchanged if
# rotation is enabled later.
# Fixed name rather than name_prefix, so CI can construct it from project and
# environment alone. The alternative — having CI read it from Terraform state —
# would mean granting CI read access to a file that holds the database password
# in plaintext.
#
# A fixed name is only safe here because recovery_window_in_days is 0. With the
# default window the name would stay reserved after a destroy and tomorrow's
# apply would collide with it.
resource "aws_secretsmanager_secret" "database" {
  name                    = "${local.secret_prefix}/db"
  description             = "Postgres connection details for ${local.name}"
  recovery_window_in_days = 0

  tags = {
    Name = "${local.name}-db-secret"
  }
}

resource "aws_secretsmanager_secret_version" "database" {
  secret_id = aws_secretsmanager_secret.database.id

  secret_string = jsonencode({
    engine   = "postgres"
    username = var.db_username
    password = random_password.db.result
    host     = aws_db_instance.main.address
    port     = aws_db_instance.main.port
    dbname   = var.db_name
  })
}

# -------------------------------------------------------------- application

resource "random_password" "jwt_access" {
  length  = 64
  special = false
}

resource "random_password" "jwt_refresh" {
  length  = 64
  special = false
}

# Seed account passwords. These log in to the demo storefront, so they are
# generated rather than left at the development defaults baked into the image.
resource "random_password" "seed_admin" {
  length  = 24
  special = false
}

resource "random_password" "seed_customer" {
  length  = 24
  special = false
}

resource "aws_secretsmanager_secret" "app" {
  name                    = "${local.secret_prefix}/app"
  description             = "Application signing keys and seed credentials for ${local.name}"
  recovery_window_in_days = 0

  tags = {
    Name = "${local.name}-app-secret"
  }
}

resource "aws_secretsmanager_secret_version" "app" {
  secret_id = aws_secretsmanager_secret.app.id

  # Key names match the jmesPath entries in the chart's SecretProviderClass.
  secret_string = jsonencode({
    jwtAccessSecret      = random_password.jwt_access.result
    jwtRefreshSecret     = random_password.jwt_refresh.result
    seedAdminPassword    = random_password.seed_admin.result
    seedCustomerPassword = random_password.seed_customer.result
  })
}
